FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY core/go.mod core/go.sum ./
RUN go mod download

COPY core/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /poll-service ./cmd/server/main.go

FROM alpine:3.19

RUN apk add --no-cache ca-certificates

WORKDIR /root/

COPY --from=builder /poll-service .

EXPOSE 8080

CMD ["./poll-service"]
