FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY bot/go.mod bot/go.sum ./
RUN go mod download

COPY bot/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /telegram-bot ./cmd/telegram-bot/main.go

FROM alpine:3.19

RUN apk add --no-cache ca-certificates

WORKDIR /root/

COPY --from=builder /telegram-bot .

CMD ["./telegram-bot"]
